[package]
name = "clipboard-manager-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
clipboard = "0.5.0"
clipboard-master = "3.1.3"
gtk = { version = "0.8.2", package = "gtk4", features = ["v4_14"] }

