[package]
name = "cliprs-gtk"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
gtk4 = "0.9.0"
log = "0.4.22"
mini-redis = "0.4.1"
simple-logging = "2.0.2"
sysinfo = "0.30.13"
tokio = "1.40.0"
